Diplom/core/api/frontend/urls.py
from .views import (
    FrontendImageList, FrontendImageDetail, ImageView, ImageOperation,
    FrontendEntityList, FrontendEntityDetail, EntityView, EntityOperation,
    FrontendAuthorList, FrontendAuthorDetail, AuthorView, AuthorOperation,
    SearchDetailView, SearchView, autocompleteModel,
    ReportsView,
)
from django.conf.urls import url

urlpatterns = [
    url(r'^entitys/$', FrontendEntityList.as_view(), name='entitys-list-front'),
    url(r'^entity/(?P<pk>\d+)/$', FrontendEntityDetail.as_view(), name='entity-detail-front'),
    url(r'^entity-operation/$', EntityView.as_view(), name='entity-add'),
    url(r'^entity-operation/(?P<pk>\d+)/$', EntityView.as_view(), name='entity-change'),
    url(r'^entity/(?P<pk>\d+)/(?P<operation>\w+)/$', EntityOperation.as_view(), name='entity-operation'),

    url(r'^authors/$', FrontendAuthorList.as_view(), name='authors_list'),
    url(r'^author/(?P<pk>\d+)/$', FrontendAuthorDetail.as_view(), name='author-detail-front'),
    url(r'^author/(?P<pk>\d+)/(?P<operation>\w+)/$', AuthorOperation.as_view(), name='author-operation'),
    url(r'^author-operation/$', AuthorView.as_view(), name='author-add'),
    url(r'^author-operation/(?P<pk>\d+)/$', AuthorView.as_view(), name='author-change'),

    url(r'^images/$', FrontendImageList.as_view(), name='images-list-front'),
    url(r'^image/(?P<pk>\d+)/$', FrontendImageDetail.as_view(), name='image-detail-front'),
    url(r'^image/(?P<pk>\d+)/(?P<operation>\w+)/$', ImageOperation.as_view(), name='image-operation'),
    url(r'^image-operation/$', ImageView.as_view(), name='image-add'),
    url(r'^image-operation/(?P<pk>\d+)/$', ImageView.as_view(), name='image-change'),

    url(r'^search-detail/$', SearchDetailView.as_view(), name='search-detail'),
    url(r'^search/$', SearchView.as_view(), name='search'),

    url(r'^reports/$', ReportsView.as_view(), name='reports'),

    url(r'^ajax_calls/search/(?P<model>\w+)/', autocompleteModel, name='auto-complete'),
]

Diplom/core/api/urls.py
from .views import ImageList, ImageDetail, EntityList, EntityDetail, AuthorList, AuthorDetail
from django.conf.urls import url

urlpatterns = [
    url(r'^entitys/$', EntityList.as_view(), name='entitys-list'),
    url(r'^entity/(?P<pk>\d+)/$', EntityDetail.as_view(), name='entity-detail'),
    url(r'^authors/$', AuthorList.as_view(), name='authors_list'),
    url(r'^author/(?P<pk>\d+)/$', AuthorDetail.as_view(), name='author-detail'),
    url(r'^images/$', ImageList.as_view(), name='images-list'),
    url(r'^image/(?P<pk>\d+)/$', ImageDetail.as_view(), name='image-detail'),

]

Diplom/core/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^api/', include('core.api.urls')),
    url(r'^frontend/', include('core.api.frontend.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Diplom/info_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('core.urls')),
]

Diplom/core/models.py
from io import BytesIO
from PIL import Image as Pil_Image
import sys

from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class Category(models.Model):
    name_ru = models.TextField(verbose_name=_('Наименование'))


class Occupation(models.Model):
    name_ru = models.TextField(verbose_name=_('Название специализации'), blank=False)
    name_en = models.TextField(verbose_name=_('Occupation'), blank=False)


class Land(models.Model):
    name_ru = models.TextField(verbose_name=_('Страна'), blank=False)
    name_en = models.TextField(verbose_name=_('Land'), blank=False)


class Entity(models.Model):
    name_ru = models.TextField(verbose_name=_('Наименование'), blank=True, default='', null=True)
    name_en = models.TextField(verbose_name=_('Name'), blank=True, default='', null=True)
    begin_date = models.TextField(verbose_name=_('Дата начала'), null=True)
    end_date = models.TextField(verbose_name=_('Дата окончания'), blank=True, null=True, default=None)
    description = models.TextField(verbose_name=_('Описание'), blank=True, default='', null=True)
    notes = models.TextField(verbose_name=_('Примечание'), blank=True, default='', null=True)
    source = models.TextField(verbose_name=_('Источник'), blank=True, default='', null=True)
    source_link = models.URLField(verbose_name=_('Ссылка на источник'), blank=True, default='', null=True)
    index = models.TextField(verbose_name=_('Индекс'), blank=True, default='', null=True)

    normdate = models.TextField(verbose_name=_('Нормативный контроль'), blank=True, default='', null=True)

    category = models.ManyToManyField(
        Category,
        verbose_name=_('Категория'),
    )

    main_image = models.ForeignKey(
        'Image',
        verbose_name=_('Оновное изображение'),
        blank=True,
        null=True,
        default=None,
        on_delete=models.SET_DEFAULT,
        related_name='main_entitys',
    )

    class Meta:
        ordering = ['name_ru']
        unique_together = [
            ('name_ru', 'name_en', 'index',),
        ]

    def __str__(self):
        return f'Id: {self.id}, Name: {self.name_ru if self.name_ru else self.name_en}'


class Author(models.Model):
    name_ru = models.TextField(verbose_name=_('Наименование'), blank=True, default='', null=True)
    name_en = models.TextField(verbose_name=_('Name'), blank=True, default='', null=True)
    begin_date = models.TextField(verbose_name=_('Дата рождения'), blank=True, null=True)
    end_date = models.TextField(verbose_name=_('Дата смерти'), blank=True, null=True)
    begin_work_date = models.TextField(verbose_name=_('Дата начала деятельности'), blank=True, null=True)
    end_work_date = models.TextField(verbose_name=_('Дата окончания деятельности'), blank=True, null=True)
    index = models.TextField(verbose_name=_('Индекс'), blank=True, default='', null=True)
    notes = models.TextField(verbose_name=_('Примечание'), blank=True, default='', null=True)
    gnd = models.TextField(verbose_name=_('Индекс GND'), blank=True, default='', null=True)

    occupations = models.ManyToManyField(Occupation, verbose_name=_('Специализации'), related_name='authors')
    lands = models.ManyToManyField(Land, verbose_name=_('Страны творчества'), related_name='authors')

    class Meta:
        ordering = ['name_ru']
        unique_together = [
            ('name_ru', 'name_en', 'index',),
        ]

    def __str__(self):
        return f'Id: {self.id}, Name: {self.name_ru if self.name_ru else self.name_en}'

    def add_occupations(self, occupations):
        for occupation_name in occupations:
            occupation = (
                Occupation
                .objects
                .filter(models.Q(name_ru__iexact=occupation_name) | models.Q(name_en__iexact=occupation_name))
                .first()
            )
            if occupation:
                self.occupations.add(occupation)

    def add_lands(self, lands):
        for land_name in lands:
            land = (
                Land
                .objects
                .filter(models.Q(name_ru__iexact=land_name) | models.Q(name_en__iexact=land_name))
                .first()
            )
            if land:
                self.lands.add(land)


class Image(models.Model):
    image = models.ImageField(verbose_name=_('Изображение'), blank=True, default=None, upload_to='media')
    thumb_image = models.ImageField(verbose_name='Превью', default=None, upload_to='media/thumbs', null=True)
    name_ru = models.TextField(verbose_name=_('Название'), blank=True, default='', null=True)
    name_en = models.TextField(verbose_name=_('Name'), blank=True, default='', null=True)
    description = models.TextField(verbose_name=_('Описание'), blank=True, default='', null=True)
    description_lat = models.TextField(verbose_name=_('Описание lat'), blank=True, default='', null=True)
    created_at = models.DateTimeField(verbose_name=_('Дата создания в базе'), default=timezone.now)
    modified_at = models.DateTimeField(verbose_name=_('Дата изменения в базе'), auto_now=timezone.now)
    create_date = models.TextField(verbose_name=_('Дата создания'), default='', blank=True, null=True)
    source_link = models.URLField(verbose_name=_('Ссылка на источник'), blank=True, default='', null=True)
    notes = models.TextField(verbose_name=_('Примечание'), blank=True, default='', null=True)

    index_image_mu = models.TextField(verbose_name=_('Индекс в коллекции'), blank=True, default='', null=True)
    index_image_hab = models.TextField(verbose_name=_('Индекс в коллекции HAB'), blank=True, default='', null=True)
    size = models.TextField(verbose_name=_('Размер'), blank=True, default='', null=True)
    technique = models.TextField(verbose_name=_('Техника исполнения'), blank=True, default='', null=True)
    doublet_links = models.TextField(verbose_name=_('Ссылки на дублеты'), blank=True, default='', null=True)
    catalog_links = models.TextField(verbose_name=_('Ссылки на каталоги'), blank=True, default='', null=True)

    entity = models.ForeignKey(
        Entity,
        verbose_name=_('Объект'),
        blank=True,
        null=True,
        default=None,
        related_name='images',
        on_delete=models.SET_DEFAULT,
    )

    class Meta:
        unique_together = [
            ('name_ru', 'name_en', 'index_image_mu',),
        ]

    def __str__(self):
        return f'Id: {self.id}, Name: {self.name_ru if self.name_ru else self.name_en}'

    def save(self, *args, **kwargs):
        if self.pk is not None:
            old_self = Image.objects.get(pk=self.pk)
            if old_self.image and self.image != old_self.image:
                old_self.image.delete(False)
                old_self.thumb_image.delete(False)

        if self.image and not self.thumb_image:
            img = Pil_Image.open(self.image.path)
            img.thumbnail((img.width // 10, img.height // 10))
            output = BytesIO()
            img.save(output, format='JPEG', quality=100)
            output.seek(0)
            self.thumb_image = InMemoryUploadedFile(
                output,
                'ImageField',
                "%s.jpg" % self.image.name.split('.')[0],
                'image/jpeg',
                sys.getsizeof(output),
                None,
            )
        super(Image, self).save(*args, **kwargs)

    class Meta:
        ordering = ['name_ru']


class AuthorsSpecialization(models.Model):
    SPECIALIZATIONS = (
        ('engraver', _('Гравер')),
        ('painter', _('Художник')),
        ('publisher', _('Издатель')),
    )

    specialization = models.TextField(verbose_name=_('Специальность'), choices=SPECIALIZATIONS)
    image = models.ForeignKey(Image, verbose_name=_('Изображение'), on_delete=models.CASCADE, related_name='authors')
    author = models.ForeignKey(Author, verbose_name=_('Автор'), on_delete=models.CASCADE, related_name='images')

    def __str__(self):
        return f'Image: {self.image_id}, Spec: {self.specialization}, Author: {self.author_id}'


@receiver(pre_delete, sender=Image)
def delete_image_files(sender, instance, **kwargs):
    instance.image.delete(save=False)
    instance.thumb_image.delete(save=False)

Diplom/core/api/views.py
from rest_framework import generics, permissions

from ..models import Image, Author, Entity
from .serializers import ImageSerializer, EntitySerializer, AuthorSerializer


class ImageList(generics.ListCreateAPIView):
    queryset = Image.objects.all()
    serializer_class = ImageSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)


class ImageDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Image.objects.all()
    serializer_class = ImageSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)


class AuthorList(generics.ListCreateAPIView):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)


class AuthorDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)


class EntityList(generics.ListCreateAPIView):
    queryset = Entity.objects.all()
    serializer_class = EntitySerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)


class EntityDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Entity.objects.all()
    serializer_class = EntitySerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

Diplom/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Entity


def records_list(request):
    records = Entity.objects.all().order_by('name_ru')
    return render(request, 'records_list.html', {'records': records})


def record_detail(request, id):
    record = get_object_or_404(Entity, id=id)
    return render(request, 'records_list.html', {'records': [record]})


def search_record(request):
    if request.method == 'GET':
        return render(request, 'search.html', {})
    else:
        id = request.POST['num']
        if Entity.objects.filter(id=id).exists():
            return redirect('record_detail', id=id)
        else:
            return render(request, 'search.html', {})

Diplom/core/views/entitys_view.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from ..models import Entity, Image


def entity_list(request):
    entitys_list = Entity.objects.all().order_by('name_ru').select_related('main_image')
    paginator = Paginator(entitys_list, 20)  # Выводим по 20 элементов
    page = request.GET.get('page')
    entitys = paginator.get_page(page)
    return render(request, 'pleeness/pages/gallery.html', {'entitys': entitys})


def entity_detail(request, id):
    entity = get_object_or_404(Entity, id=id)
    images = Image.objects.filter(entity__id=id).exclude(id=entity.main_image.id).select_related('author')
    return render(request, 'entity.html', {'entity': entity, 'images': images})


def search_entity(request):
    if request.method == 'GET':
        return render(request, 'search.html', {})
    else:
        id = request.POST['num']
        if Entity.objects.filter(id=id).exists():
            return redirect('entity', id=id)
        else:
            return render(request, 'search.html', {})

Diplom/core/templates/author-detail.html
{% extends "./base.html" %}

{% block content %}
<div class="wrapp row3">
  <main class="hoc container clear">
    <td class="content">
      {% if user.is_authenticated %}
      <div class="div1">
        <form  action="delete/" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
      </div>
      <div class="div1">
        <form action="change/" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-medium">Изменить</button>
        </form>
      </div>
      <div>
        <p></p>
      {% endif %}
      <h2>Индекс: {% if index %} {{ index }} {% else %} не указан {% endif %}</h2>
        <table border= "1">
          <tr>
            <td>Имя (рус.)</td>
            <td>{{name_ru}}</td>
          </tr>
          <tr>
            <td>Имя (lat.)</td>
            <td>{{name_en}}</td>
          </tr>
          <tr>
            <td>Индекс GND:</td>
            <td>{{ gnd }}</td>
          </tr>
          {% if begin_date or end_date %}
          <tr>
            <td>Годы жизни:</td>
            <td>{% if begin_date %}{{ begin_date }}{% else %}...{% endif %} - {% if end_date %}{{ end_date }}{% else %}...{% endif %}</td>
          </tr>
          {% elif begin_work_date or end_work_date %}
          <tr>
            <td>Годы творчества:</td>
            <td>{% if begin_work_date %}{{ begin_work_date }}{% else %}...{% endif %} - {% if end_work_date %}{{ end_work_date }}{% else %}...{% endif %}</td>
          </tr>
          {% else %}
          <tr>
            <td>Годы жизни:</td>
            <td>Неизвестны</td>
          </tr>
          {% endif %}

          {% if user.is_authenticated %}
          {% if notes %}
          <tr>
            <td>Заметки:</td>
            <td>{{ notes }}</td>
          </tr>
          {% endif %}
          {% endif %}
          <tr>
            <td>Специализации:</td>
            {% if occupations %}
            <td>{% for occupation in occupations %}{{occupation.name_ru}}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
            {% else %}
            <td>Неизвестны</td>
            {% endif %}
          </tr>
          <tr>
            <td>Страны:</td>
            {% if lands %}
            <td>{% for land in lands %}{{land.name_ru}}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
            {% else %}
            <td>Неизвестны</td>
            {% endif %}
          </tr>
          {% if images %}
          {% regroup images by specialization as image_list %}
          {% for image in image_list %}
            <tr>
              <td>{{image.grouper}}</td>
              <td>
                {% for item in image.list %}
                  <div><a href="/frontend/image/{{ item.image_id }}/">{% if item.image_ru %}{{ item.image_ru }}{% else %}{{item.image_en}}{% endif %}</a></div>
                {% endfor %}
              </td>
          {% endfor %}
        {% else %}
          <tr>
            <td colspan="2">Работы неизвестны</td>
          </tr>
        {% endif %}
        </table>
    </td>
  </main>
</div>


{% endblock %}

Diplom/core/templates/author-list.html
{% extends "./base.html" %}

{% block content %}
<div class="wrapp row3">
  <main class="hoc container clear">
    <td class="content">
      {% if user.is_authenticated %}
      <div class="div1">
        <form  action="/frontend/author-operation/" method="GET">
          <button type="submit" class="btn btn-danger">Создать</button>
        </form>
      </div>
        <p></p>
      {% endif %}
      <h2>Список авторов</h2>
      <div>
        <table border= "1">
          {% for author in results %}
          <tr>
            <td width="70%">
              <div>
                <a href="/frontend/author/{{ author.id }}/">
                  {{author.name_ru}}(lat:{{author.name_en}}) (
                    {% if author.begin_date or author.end_date %}
                    {% if author.begin_date %} {{ author.begin_date }}{% else %}...{% endif %} - {% if author.end_date %}{{ author.end_date }}{% else %}...{% endif %}
                    {% elif author.begin_work_date or author.end_work_date %}
                    {% if author.begin_work_date %} {{ author.begin_work_date }}{% else %}...{% endif %} - {% if author.end_work_date %}{{ author.end_work_date }}{% else %}...{% endif %}
                    {% else %}Годы жизни неизвестны{% endif %})
                </a>
              </div>
            </td>
          </tr>
          {% endfor %}
        </table>
        <nav class="pagination">
        <ul>
          <span class="step-links">
          {% if previous %}
            <li><a href="{{ previous}}">&laquo;</a></li>
          {% endif %}
          {% if next %}
            <li><a href="{{ next }}">&raquo;</a></li>
          {% endif %}
          </span>
        </ul>
      </nav>
    </div>
  </main>
</div>

{% endblock %}

Diplom/core/templates/base.html
{% load static %}
{% load i18n %}
{% load rest_framework %}
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
<title>InfoSystem</title>
<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="{% static 'layout/styles/layout.css' %}" rel="stylesheet" type="text/css" media="all">
<!--<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />-->
</head>
<body id="top">
<div class="wrapp row0">
  <div id="topbar" class="hoc clear">
    <div class="fl_right">
      <ul class="nospace inline pushright">
        {% block userlinks %}
          {% if user.is_authenticated %}
            {% optional_logout request user %}
          {% else %}
            {% optional_login request %}
          {% endif %}
        {% endblock %}
      </ul>
    </div>
  </div>
</div>
<div class="wrapp row1">
  <header id="header" class="hoc clear">
    <div id="logo" class="fl_left">
      <h1>Коллекция портретов</h1>
    </div>
    <div id="search" class="fl_right">
      <form class="clear" method="get" action="/frontend/search/">
        <fieldset>
          <legend>Поиск:</legend>
          <input name="query" type="search" value="" placeholder="Введите для поиска&hellip;">
          <button class="fa fa-search" type="submit" title="Search"><em>Search</em></button>
        </fieldset>
      </form>
    </div>
  </header>
</div>
<div class="wrapp row2">
  <nav id="mainav" class="hoc clear">
    <ul class="clear">
      <li><a href="/frontend/images/">Изображения</a></li>
      <li><a href="/frontend/entitys/">Люди</a></li>
      <li><a href="/frontend/authors/">Авторы</a></li>
      <li><a href="/frontend/search-detail/">Расширенный поиск</a></li>
      {% if user.is_authenticated %}
        <li><a href="/frontend/reports/">Выгрузить отчеты</a></li>
      {% endif %}
    </ul>
  </nav>
</div>

{% block content %}{% endblock %}

<a id="backtotop" href="#top"><i class="fa fa-chevron-up"></i></a>
<!-- JAVASCRIPTS -->
<script src="{% static 'layout/scripts/jquery.backtotop.js' %}"></script>
{% block custom_js %}{% endblock %}
</body>
</html>

Diplom/core/templates/image-detail.html
{% extends "./base.html" %}

{% block content %}
<div class="wrapp row3">
  <main class="hoc container clear">
    <td class="content">
      {% if user.is_authenticated %}
      <div class="div1">
        <form  action="delete/" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Удалить</button>
        </form>
      </div>
      <div class="div1">
        <form action="change/" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-medium">Изменить</button>
        </form>
      </div>
      <div>
        <p></p>
      {% endif %}
      <h2>Подробная информация о изображении</h2>
      <div>
        <table border= "1">
          <tr>
            <td width="20.0%">Название (рус.)</td>
            <td>{{name_ru}}</td>
            <td style="vertical-align:top" rowspan="100" width="35.0%" height="35.0%"><a href="{{ image }}"><img src="{% if image %}{{ image }} {% else %} /media/no-image.jpg {% endif %}" alt=""></a></td>
          </tr>
          <tr>
            <td>Название (lat.)</td>
            <td>{{name_en}}</td>
          </tr>
          <tr>
            <td>Изображен</td>
            <td>
              <div><a href="/frontend/entity/{{entity.id}}/">{% if entity.name_ru %} {{ entity.name_ru }} {% else %} {{ entity.name_en }} {% endif %}</a></div>
            </td>
          </tr>
          <tr>
            <td>Индекс в коллекции</td>
            <td>{{ index_image_mu }}</td>
          </tr>
          <tr>
            <td>Индекс в коллекции HAB</td>
            <td>{{ index_image_hab }}</td>
          </tr>
          <tr>
            <td>Описание</td>
            <td>{% if description %} {{ description }} {% else %} {{ description_lat }} {% endif %}</td>
          </tr>
          <tr>
            <td>Размер</td>
            <td>{{ size }}</td>
          </tr>
          <tr>
            <td>Техника исполнения</td>
            <td>{{ technique }}</td>
          </tr>
          <tr>
            <td>Ссылка на источник</td>
            <td>{{ source_link }}</td>
          </tr>
          <tr>
            <td>Ссылки на дублеты</td>
            <td>{{ doublet_links }}</td>
          </tr>
          <tr>
            <td>Ссылки на каталоги</td>
            <td>{{ catalog_links }}</td>
          </tr>
          {% if authors %}
          {% regroup authors by specialization as author_list %}
          {% for author in author_list %}
            <tr>
              <td>{{author.grouper}}</td>
              <td>
                {% for item in author.list %}
                  <div><a href="/frontend/author/{{item.author.id}}/">{% if item.author.name_ru %} {{ item.author.name_ru }} {% else %} {{ item.author.name_en }} {% endif %}</a></div>
                {% endfor %}
              </td>
          {% endfor %}
        {% else %}
          <tr>
            <td colspan="2">Автор неизвестен</td>
          </tr>
        {% endif %}
        </table>
    </div>
  </main>
</div>


{% endblock %}

Diplom/core/templates/image-list.html
{% extends "./base.html" %}

{% block content %}
<div class="wrapp row3">
  <main class="hoc container clear">
      {% if user.is_authenticated %}
      <div class="div1">
        <form  action="/frontend/image-operation/" method="GET">
          <button type="submit" class="btn btn-danger">Создать</button>
        </form>
      </div>
        <p></p>
      {% endif %}
    <div class="content">
     <style>

    </style>

      <div id="gallery">
        <figure>
          <header class="heading">Галерея изображений</header>
          <div class="gallery3">
            {% for entity in results %}
              <div class="ramka"><a href="/frontend/image/{{ entity.id }}/"><img width="100%" height="100%" src="{{ entity.thumb_image }}" alt=""></a></div>
            {% endfor %}
          </div>

        </figure>
      </div>
      <nav class="pagination">
        <ul>
          <span class="step-links">
          {% if previous %}
            <li><a href="{{ previous }}">&laquo;</a></li>
          {% endif %}
          {% if next %}
            <li><a href="{{ next }}">&raquo;</a></li>
          {% endif %}
          </span>
        </ul>
      </nav>
    </div>
    <div class="clear"></div>
  </main>
</div>
{% endblock %}

Diplom/core/templates/report.html
{% extends "./base.html" %}

{% block content %}
<link rel="stylesheet" href="http://code.jquery.com/ui/1.8.18/themes/base/jquery-ui.css" type="text/css" media="all" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>

<div class="wrapp row3">
  <main class="hoc container clear">
    {% if user.is_authenticated %}
        <form action="." method="post" enctype="multipart/form-data">
          <table border= "1">
          {% csrf_token %}
          {% for field in form %}
          <tr>
            <td width="15%">{{ field.label }}</td>
            <td width="85%">{{ field }}</td>
          </tr>
          {% endfor %}
          </table>
          <button type="submit" class="save btn btn-default">Cформировать</button>
          <button type="reset" class="delete btn btn-default">Отменить</button>
        </form>
      {% block manual_fields %}
      {% endblock %}
    {% else %}
      <h2>Доступно только авторизованным пользователям</h2>
    {% endif %}
  </main>
</div>

{% endblock %}

{% block custom_js %}
<script>
$(function() {
  $('[id="id_author"]').autocomplete({
    source: "/frontend/ajax_calls/search/author/",
    minLength: 2,
    formatItem: function(row) { return row[1] + ' (' + row[0] + ')'; },
    formatResult: function(row) { return row[0]; },
  });
});

$(function() {
  $('[id="id_entity"]').autocomplete({
    source: "/frontend/ajax_calls/search/entity/",
    minLength: 2,
    formatItem: function(row) { return row[1] + ' (' + row[0] + ')'; },
    formatResult: function(row) { return row[0]; },
  });
});

</script>
{% endblock %}